### ISSUE TITLE
Parallels with maru's design?

### ISSUE THREAD

**Issue by zunzster** [TurtleKitty/Sexy#1]
This very cool work reminds me of Ian Piumarta's maru (http://piumarta.com/software/maru/)

Admittedly, my knowledge of Lisp interpreters is limited but how macro is just a syntactic wrapper for 'operator' to pass the body unevaluated is strikingly similar to how maru macros use 'form' as their wrapper construct.

**Comment by TurtleKitty** [comment]
Thanks for the compliment.  I've looked at Maru before, but never fully grokked it, so I can't claim direct inspiration.  It seems like a cool project, and well-respected by the denizens of LtU, so I should probably give it another look; maybe I'll understand it better now that I've written an interpreter. :)
